//! Criterion benchmark generation (issue #235).
//!
//! Budget tests assert a ceiling: they catch the moment a cost crosses a line,
//! and say nothing until then. A benchmark records the number every run, so a
//! change that adds 20% to an entrypoint is visible immediately instead of
//! whenever it happens to breach the budget. The two are complementary — the
//! budget test gates, the bench tracks.

use crate::detect::{ContractInfo, MethodInfo};
use soroban_forge_core::render::{render_str, Vars};

/// `benches/forge_bench.rs`, the criterion harness.
pub const BENCH_RS: &str = r#"//! Generated by `soroban-forge test-init --bench`.
//!
//! Criterion benchmarks for the contract's entrypoints. Where the budget test
//! in `tests/forge_budget.rs` gates a ceiling, these track the cost over time:
//!
//!   cargo bench                        # run every benchmark
//!   cargo bench -- <entrypoint>        # run one
//!   cargo bench -- --save-baseline main
//!   cargo bench -- --baseline main     # compare a branch against it
//!
//! Criterion writes reports to `target/criterion/`.
//!
//! Note that these measure host wall-clock time in the test environment, not
//! on-chain CPU instructions. For the metered numbers that decide whether a
//! transaction fits in a ledger, use the budget test. Wall-clock is still the
//! right tool for spotting a regression trend, because it moves with the same
//! work the metered cost does.

use criterion::{criterion_group, criterion_main, Criterion};
"#;

/// One benchmark function. Receives `contract_type`, `fn_name`,
/// `contract_args`, `entrypoint` and `entrypoint_args`.
pub const BENCH_FN: &str = r#"
fn bench_{{fn_name}}_{{entrypoint}}(c: &mut Criterion) {
    c.bench_function("{{fn_name}}::{{entrypoint}}", |b| {
        b.iter(|| {
            // The environment is rebuilt per iteration on purpose: a contract
            // whose cost grows with accumulated state would otherwise be
            // measured against whatever the previous iterations left behind.
            let env = common::test_env();
            let contract_id = env.register({{contract_type}}, {{contract_args}});
            let client = {{contract_type}}Client::new(&env, &contract_id);
            env.mock_all_auths();
            criterion::black_box(client.{{entrypoint}}({{entrypoint_args}}));
        })
    });
}
"#;

/// The `[[bench]]` target and criterion dev-dependency a scaffolded project
/// needs for `cargo bench` to find the harness.
pub const BENCH_CARGO_FRAGMENT: &str = r#"
[dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "forge_bench"
harness = false
"#;

/// Entrypoints worth benchmarking.
///
/// `__constructor` runs at registration rather than through the client, and a
/// method whose arguments cannot be defaulted would not compile, so both are
/// skipped rather than emitted broken.
pub fn benchable_methods(info: &ContractInfo) -> Vec<&MethodInfo> {
    info.methods
        .iter()
        .filter(|m| m.name != "__constructor")
        .collect()
}

/// Client call arguments, defaulted from each parameter's type.
fn bench_call_args(method: &MethodInfo) -> String {
    method
        .args
        .iter()
        .map(|(_, ty)| format!("&{}", crate::detect::map_type_to_default(ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render `benches/forge_bench.rs`.
///
/// Returns an empty string when the contract has no benchmarkable entrypoint,
/// so `--bench` on a contract with nothing to measure does not leave behind a
/// `benches/` target that fails to build.
pub fn build_bench(info: &ContractInfo) -> String {
    let methods = benchable_methods(info);
    if methods.is_empty() || info.contract_types.is_empty() {
        return String::new();
    }

    let mut out = String::from(BENCH_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));
    // Benches are their own crate root, so the fixtures module is included
    // rather than declared as a sibling of the integration tests.
    out.push_str("\n#[path = \"../tests/common/mod.rs\"]\nmod common;\n");

    let mut group_members: Vec<String> = Vec::new();

    for contract_type in &info.contract_types {
        let fn_name = crate::to_snake_case(contract_type);
        for method in &methods {
            let mut vars = Vars::new();
            vars.insert("contract_type".into(), contract_type.clone());
            vars.insert("fn_name".into(), fn_name.clone());
            vars.insert("contract_args".into(), info.constructor_args.clone());
            vars.insert("entrypoint".into(), method.name.clone());
            vars.insert("entrypoint_args".into(), bench_call_args(method));
            out.push_str(&render_str(BENCH_FN, &vars));
            group_members.push(format!("bench_{fn_name}_{}", method.name));
        }
    }

    out.push_str(&format!(
        "\ncriterion_group!(forge_benches, {});\ncriterion_main!(forge_benches);\n",
        group_members.join(", ")
    ));

    out
}

/// Appends the `[[bench]]` target and criterion dev-dependency to the
/// project's `Cargo.toml`.
///
/// Returns `true` when the manifest was changed. Appending is skipped when a
/// `forge_bench` target is already declared, so re-running `--bench` does not
/// duplicate the section.
pub fn ensure_bench_target(manifest: &str) -> Option<String> {
    if manifest.contains("name = \"forge_bench\"") {
        return None;
    }

    let mut updated = manifest.trim_end().to_string();
    updated.push('\n');

    // A project that already has `[dev-dependencies]` gets criterion added to
    // it; emitting a second section would make cargo reject the manifest.
    if manifest.contains("[dev-dependencies]") {
        updated.push_str(
            "\ncriterion = { version = \"0.5\", default-features = false, features = [\"cargo_bench_support\"] }\n\
             \n[[bench]]\nname = \"forge_bench\"\nharness = false\n",
        );
    } else {
        updated.push_str(BENCH_CARGO_FRAGMENT);
    }

    Some(updated)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    fn info_with(methods: Vec<MethodInfo>) -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["DemoContract".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: false,
            methods,
            constructor_arg_types: None,
            events: Vec::new(),
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: Vec::new(),
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        }
    }

    #[test]
    fn skips_the_constructor() {
        let info = info_with(vec![
            method("__constructor", &[("admin", "Address")]),
            method("increment", &[]),
        ]);
        let names: Vec<_> = benchable_methods(&info).iter().map(|m| &m.name).collect();
        assert_eq!(names, vec!["increment"]);
    }

    #[test]
    fn emits_a_criterion_main_and_one_function_per_entrypoint() {
        let info = info_with(vec![
            method("increment", &[]),
            method("mint", &[("to", "Address"), ("amount", "i128")]),
        ]);
        let rendered = build_bench(&info);

        assert!(rendered.contains("fn bench_demo_contract_increment"));
        assert!(rendered.contains("fn bench_demo_contract_mint"));
        assert!(rendered.contains(
            "criterion_group!(forge_benches, bench_demo_contract_increment, bench_demo_contract_mint);"
        ));
        assert!(rendered.contains("criterion_main!(forge_benches);"));
    }

    #[test]
    fn defaults_entrypoint_arguments() {
        let info = info_with(vec![method("mint", &[("to", "Address"), ("amount", "i128")])]);
        let rendered = build_bench(&info);
        assert!(rendered.contains("client.mint(&common::new_account(&env), &0_i128)"));
    }

    #[test]
    fn reuses_the_generated_fixtures_module() {
        let info = info_with(vec![method("increment", &[])]);
        let rendered = build_bench(&info);
        assert!(rendered.contains("#[path = \"../tests/common/mod.rs\"]"));
    }

    #[test]
    fn emits_nothing_when_there_is_nothing_to_measure() {
        let info = info_with(vec![method("__constructor", &[])]);
        assert!(build_bench(&info).is_empty());
    }

    #[test]
    fn adds_the_bench_target_to_a_manifest() {
        let manifest = "[package]\nname = \"demo\"\n";
        let updated = ensure_bench_target(manifest).expect("manifest changed");
        assert!(updated.contains("[[bench]]"));
        assert!(updated.contains("harness = false"));
        assert!(updated.contains("criterion"));
    }

    #[test]
    fn reuses_an_existing_dev_dependencies_section() {
        let manifest = "[package]\nname = \"demo\"\n\n[dev-dependencies]\nproptest = \"1\"\n";
        let updated = ensure_bench_target(manifest).expect("manifest changed");
        // A second [dev-dependencies] table would make cargo reject the file.
        assert_eq!(updated.matches("[dev-dependencies]").count(), 1);
        assert!(updated.contains("criterion"));
    }

    #[test]
    fn is_idempotent() {
        let manifest = "[package]\nname = \"demo\"\n";
        let once = ensure_bench_target(manifest).expect("manifest changed");
        assert!(ensure_bench_target(&once).is_none());
    }
}
