//! Upgrade / migration test generation (issue #234).
//!
//! An upgradeable contract's most dangerous failure is silent state loss: the
//! new wasm lays out storage differently, the upgrade succeeds, and the old
//! values are simply unreachable. The generated test pins the property that
//! matters — write state under v1, upgrade, read it back — so a migration that
//! drops state fails the suite instead of production.

use crate::detect::{ContractInfo, MethodInfo};
use crate::to_snake_case;
use soroban_forge_core::render::{render_str, Vars};

/// Header of the generated upgrade test file.
pub const UPGRADE_TEST_RS: &str = r#"//! Generated by `soroban-forge test-init`. Upgrade / migration safety.
//!
//! The test writes state through v1, performs the upgrade, and asserts the
//! state is still readable afterwards. A failure means the migration dropped
//! or moved state that the old version had written — the class of bug that is
//! unrecoverable once it reaches mainnet.
//!
//! ## Pointing this at a real v2
//!
//! The test ships `#[ignore]`d: a migration test needs a second wasm, and
//! there is no v2 to point at when the harness is generated. Upgrading the
//! contract to its own wasm would not fill the gap either — with only one
//! storage layout involved, the exact bug this test exists to catch cannot
//! occur.
//!
//! To turn it into a genuine migration test, build the next version and point
//! the test at it:
//!
//! 1. Build v2 to wasm:
//!    `cargo build --target wasm32v1-none --release -p <your-v2-crate>`
//! 2. Declare it next to this file so the test binary can embed it:
//!    ```ignore
//!    mod v2 {
//!        soroban_sdk::contractimport!(
//!            file = "../target/wasm32v1-none/release/<your_v2_crate>.wasm"
//!        );
//!    }
//!    ```
//! 3. Replace the body of the `v2_wasm_hash` helper below with
//!    `env.deployer().upload_contract_wasm(v2::WASM)`.
//! 4. Remove the `#[ignore]`.
//!
//! Everything else in the test stays as-is: the assertions are about state
//! surviving, not about which wasm replaced which.

mod common;
"#;

/// The v2 upload helper. Emitted once per file, ahead of the per-contract
/// tests, so a crate with two `#[contract]` types does not define it twice.
pub const UPGRADE_HELPER: &str = r#"
/// Uploads the wasm this contract will be upgraded *to*, returning its hash.
///
/// Replace the body with your v2 build — see the module docs at the top of this
/// file. Until then the test below is `#[ignore]`d and this is never called.
fn v2_wasm_hash(env: &soroban_sdk::Env) -> soroban_sdk::BytesN<32> {
    // mod v2 {
    //     soroban_sdk::contractimport!(
    //         file = "../target/wasm32v1-none/release/<your_v2_crate>.wasm"
    //     );
    // }
    // return env.deployer().upload_contract_wasm(v2::WASM);
    let _ = env;
    unimplemented!("point this at your v2 wasm — see the module docs")
}
"#;

/// The per-contract upgrade test. Receives `contract_type`, `fn_name`,
/// `contract_args`, `upgrade_method`, `upgrade_args`, `state_setup` and
/// `state_assert`.
///
/// The test is `#[ignore]`d because a genuine migration test needs a second
/// wasm, and there is no v2 to point at when the harness is generated. This
/// follows the same convention as the generated smoke test for a contract with
/// a `__constructor`: emit the real test, ignore it, and say in the file
/// exactly what to supply. Un-ignoring it without a v2 would prove nothing —
/// upgrading a contract to its own wasm cannot surface a storage-layout
/// change, because only one layout is involved.
pub const UPGRADE_TEST_FN: &str = r#"
#[test]
#[ignore = "supply a v2 wasm in `v2_wasm_hash` first — see the module docs"]
fn {{fn_name}}_survives_upgrade_with_state_intact() {
    let env = common::test_env();
    let contract_id = env.register({{contract_type}}, {{contract_args}});
    let client = {{contract_type}}Client::new(&env, &contract_id);

    // --- v1: write state -------------------------------------------------
{{state_setup}}

    // --- upgrade ---------------------------------------------------------
    let new_wasm_hash = v2_wasm_hash(&env);

    // The upgrade entrypoint is admin-gated; `mock_all_auths` stands in for
    // the admin signature so the test exercises the migration, not the auth.
    env.mock_all_auths();
    client.{{upgrade_method}}({{upgrade_args}});

    // --- v2: the state written before the upgrade must still be there ----
{{state_assert}}
}
"#;

/// An upgrade-style entrypoint detected on the contract.
#[derive(Debug, Clone, PartialEq)]
pub struct UpgradeEntrypoint {
    /// The method itself.
    pub method: MethodInfo,
    /// Name of the argument carrying the new wasm hash, when there is one.
    pub wasm_hash_arg: Option<String>,
}

/// Method names that mean "replace this contract's code".
const UPGRADE_NAMES: [&str; 4] = ["upgrade", "upgrade_contract", "set_wasm", "migrate"];

/// True when `ty` is the 32-byte hash an upgrade entrypoint takes.
fn is_wasm_hash_type(ty: &str) -> bool {
    let ty = ty.replace('&', "");
    let ty = ty.trim();
    ty.ends_with("BytesN<32>")
}

/// Finds the contract's upgrade entrypoint, if it has one.
///
/// Detection is deliberately narrow: an upgrade test is only meaningful for a
/// contract that really can replace its own wasm, and a false positive would
/// emit a test that cannot compile. A method qualifies when its name is one of
/// the known upgrade names, or when it takes a `BytesN<32>` argument whose name
/// mentions wasm.
pub fn detect_upgrade_entrypoint(methods: &[MethodInfo]) -> Option<UpgradeEntrypoint> {
    for method in methods {
        let name_matches = UPGRADE_NAMES.contains(&method.name.as_str());
        let hash_arg = method
            .args
            .iter()
            .find(|(name, ty)| is_wasm_hash_type(ty) && (name_matches || name.contains("wasm")));

        if let Some((arg_name, _)) = hash_arg {
            return Some(UpgradeEntrypoint {
                method: method.clone(),
                wasm_hash_arg: Some(arg_name.clone()),
            });
        }
    }
    None
}

/// Builds the client call arguments for the upgrade entrypoint, passing the
/// uploaded hash for the wasm argument and defaults for anything else.
fn upgrade_call_args(entry: &UpgradeEntrypoint) -> String {
    entry
        .method
        .args
        .iter()
        .map(|(name, ty)| {
            if Some(name) == entry.wasm_hash_arg.as_ref() {
                "&new_wasm_hash".to_string()
            } else {
                format!("&{}", crate::detect::map_type_to_default(ty))
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Picks a read-only entrypoint whose value can be compared across the
/// upgrade. Prefers a zero-argument getter: it needs no fixture setup and its
/// result depends only on stored state, which is exactly what is under test.
fn pick_state_reader(info: &ContractInfo, upgrade_method: &str) -> Option<MethodInfo> {
    info.methods
        .iter()
        .find(|m| {
            m.name != upgrade_method
                && m.name != "__constructor"
                && m.args.is_empty()
                && !UPGRADE_NAMES.contains(&m.name.as_str())
        })
        .cloned()
}

/// Renders the "write state" and "assert state" halves of the test.
///
/// With a readable getter the assertion is real: the value is captured before
/// the upgrade and compared after. Without one, the test still proves the
/// upgrade entrypoint works, and says plainly in a comment what to add.
fn state_sections(info: &ContractInfo, upgrade_method: &str) -> (String, String) {
    match pick_state_reader(info, upgrade_method) {
        Some(reader) => (
            format!(
                "    // `{name}` reads stored state, so its value before and after the\n\
                 \x20   // upgrade is a direct check that the migration preserved it.\n\
                 \x20   let before = client.{name}();",
                name = reader.name
            ),
            format!(
                "    let after = client.{name}();\n\
                 \x20   assert_eq!(\n\
                 \x20       before, after,\n\
                 \x20       \"`{name}` changed across the upgrade — the migration did not preserve state\"\n\
                 \x20   );",
                name = reader.name
            ),
        ),
        None => (
            "    // No zero-argument getter was detected, so there is nothing to read\n\
             \x20   // back automatically. Call the entrypoint that writes the state you\n\
             \x20   // care about here, and assert on it below."
                .to_string(),
            "    // Add the matching read here, e.g.:\n\
             \x20   //     assert_eq!(client.your_getter(), expected);\n\
             \x20   // Reaching this line already proves the upgrade entrypoint itself works."
                .to_string(),
        ),
    }
}

/// Render `tests/forge_upgrade.rs`.
///
/// Returns an empty string when the contract exposes no upgrade entrypoint, so
/// the file is only emitted where it means something.
pub fn build_upgrade_test(info: &ContractInfo) -> String {
    let Some(entry) = detect_upgrade_entrypoint(&info.methods) else {
        return String::new();
    };

    let mut out = String::from(UPGRADE_TEST_RS);
    out.push_str(&format!(
        "use {}::{{ {} }};\n",
        info.crate_name,
        info.contract_types
            .iter()
            .flat_map(|ct| [ct.clone(), format!("{ct}Client")])
            .collect::<Vec<_>>()
            .join(", ")
    ));

    out.push_str(UPGRADE_HELPER);

    let (state_setup, state_assert) = state_sections(info, &entry.method.name);

    for contract_type in &info.contract_types {
        let mut vars = Vars::new();
        vars.insert("contract_type".into(), contract_type.clone());
        vars.insert("fn_name".into(), to_snake_case(contract_type));
        vars.insert("contract_args".into(), info.constructor_args.clone());
        vars.insert("upgrade_method".into(), entry.method.name.clone());
        vars.insert("upgrade_args".into(), upgrade_call_args(&entry));
        vars.insert("state_setup".into(), state_setup.clone());
        vars.insert("state_assert".into(), state_assert.clone());
        out.push_str(&render_str(UPGRADE_TEST_FN, &vars));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method(name: &str, args: &[(&str, &str)]) -> MethodInfo {
        MethodInfo {
            name: name.to_string(),
            args: args
                .iter()
                .map(|(n, t)| (n.to_string(), t.to_string()))
                .collect(),
        }
    }

    #[test]
    fn detects_the_upgradeable_template_entrypoint() {
        // Exactly the signature in templates/upgradeable.
        let methods = vec![
            method("__constructor", &[("admin", "Address")]),
            method("admin", &[]),
            method("upgrade", &[("new_wasm_hash", "BytesN<32>")]),
        ];
        let found = detect_upgrade_entrypoint(&methods).expect("upgrade entrypoint");
        assert_eq!(found.method.name, "upgrade");
        assert_eq!(found.wasm_hash_arg.as_deref(), Some("new_wasm_hash"));
    }

    #[test]
    fn detects_a_wasm_hash_argument_under_another_name() {
        let methods = vec![method("apply_update", &[("wasm_hash", "BytesN<32>")])];
        assert!(detect_upgrade_entrypoint(&methods).is_some());
    }

    #[test]
    fn ignores_contracts_with_no_upgrade_path() {
        let methods = vec![
            method("mint", &[("to", "Address"), ("amount", "i128")]),
            method("balance", &[("of", "Address")]),
        ];
        assert!(detect_upgrade_entrypoint(&methods).is_none());
    }

    #[test]
    fn does_not_mistake_an_unrelated_bytesn_for_an_upgrade() {
        // A merkle proof root is `BytesN<32>` too, but this is not an upgrade.
        let methods = vec![method("claim", &[("root", "BytesN<32>")])];
        assert!(detect_upgrade_entrypoint(&methods).is_none());
    }

    #[test]
    fn upgrade_call_args_passes_the_uploaded_hash() {
        let entry = UpgradeEntrypoint {
            method: method("upgrade", &[("new_wasm_hash", "BytesN<32>")]),
            wasm_hash_arg: Some("new_wasm_hash".into()),
        };
        assert_eq!(upgrade_call_args(&entry), "&new_wasm_hash");
    }

    #[test]
    fn upgrade_call_args_defaults_other_arguments() {
        let entry = UpgradeEntrypoint {
            method: method(
                "upgrade",
                &[("caller", "Address"), ("new_wasm_hash", "BytesN<32>")],
            ),
            wasm_hash_arg: Some("new_wasm_hash".into()),
        };
        assert_eq!(
            upgrade_call_args(&entry),
            "&common::new_account(&env), &new_wasm_hash"
        );
    }

    #[test]
    fn state_reader_prefers_a_zero_argument_getter() {
        let info = ContractInfo {
            methods: vec![
                method("admin", &[]),
                method("balance", &[("of", "Address")]),
                method("upgrade", &[("new_wasm_hash", "BytesN<32>")]),
            ],
            ..sample_info()
        };
        let reader = pick_state_reader(&info, "upgrade").expect("reader");
        assert_eq!(reader.name, "admin");
    }

    #[test]
    fn state_sections_fall_back_to_guidance_without_a_getter() {
        let info = ContractInfo {
            methods: vec![method("upgrade", &[("new_wasm_hash", "BytesN<32>")])],
            ..sample_info()
        };
        let (setup, assert_section) = state_sections(&info, "upgrade");
        assert!(setup.contains("No zero-argument getter"));
        assert!(assert_section.contains("Add the matching read"));
    }

    #[test]
    fn emits_nothing_for_a_non_upgradeable_contract() {
        let info = ContractInfo {
            methods: vec![method("mint", &[("to", "Address")])],
            ..sample_info()
        };
        assert!(build_upgrade_test(&info).is_empty());
    }

    #[test]
    fn ships_ignored_with_a_reason_and_a_single_helper() {
        let info = ContractInfo {
            contract_types: vec!["First".into(), "Second".into()],
            methods: vec![
                method("admin", &[]),
                method("upgrade", &[("new_wasm_hash", "BytesN<32>")]),
            ],
            ..sample_info()
        };
        let rendered = build_upgrade_test(&info);

        // Ignored until a v2 exists: upgrading to the contract's own wasm
        // cannot surface a storage-layout change.
        assert_eq!(rendered.matches("#[ignore =").count(), 2);
        // ...but the upload helper is defined exactly once, however many
        // `#[contract]` types the crate has.
        assert_eq!(rendered.matches("fn v2_wasm_hash").count(), 1);
    }

    #[test]
    fn generated_test_documents_pointing_at_a_real_v2() {
        let info = ContractInfo {
            methods: vec![
                method("admin", &[]),
                method("upgrade", &[("new_wasm_hash", "BytesN<32>")]),
            ],
            ..sample_info()
        };
        let rendered = build_upgrade_test(&info);
        assert!(rendered.contains("Pointing this at a real v2"));
        assert!(rendered.contains("contractimport!"));
        assert!(rendered.contains("survives_upgrade_with_state_intact"));
    }

    fn sample_info() -> ContractInfo {
        ContractInfo {
            package_name: "demo".into(),
            crate_name: "demo".into(),
            contract_types: vec!["UpgradeableContract".into()],
            has_constructor: false,
            has_testutils: true,
            constructor_args: "()".into(),
            has_proptest: false,
            methods: Vec::new(),
            constructor_arg_types: None,
            events: Vec::new(),
            has_contractevent: false,
            has_token_deps: false,
            token_param_names: Vec::new(),
            init_method: None,
            has_persistent_storage: false,
            has_instance_storage: false,
            has_temporary_storage: false,
        }
    }
}
