//! Dutch Auction contract — descending price auction.
//!
//! A descending-price auction where the price decays linearly from a start
//! price to a floor price over a fixed window. The first buyer settles at
//! the current price.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum AuctionState {
    /// Initialized, waiting for seller to fund the asset.
    Pending,
    /// Funded and open for purchase.
    Open,
    /// Successfully purchased and settled.
    Settled,
    /// Canceled by seller before purchase.
    Canceled,
}

#[contracttype]
pub enum DataKey {
    Seller,
    AssetToken,
    PaymentToken,
    AssetAmount,
    StartPrice,
    FloorPrice,
    StartTime,
    Duration,
    State,
    Buyer,
    SettledPrice,
}

#[contract]
pub struct DutchAuctionContract;

#[contractimpl]
impl DutchAuctionContract {
    /// Initialize the Dutch auction.
    ///
    /// * `seller` — address selling the asset
    /// * `asset_token` — contract address of the SEP-41 token being sold
    /// * `payment_token` — contract address of the SEP-41 token used for payment
    /// * `asset_amount` — quantity of asset tokens offered for sale
    /// * `start_price` — starting price in payment tokens at start of auction
    /// * `floor_price` — minimum price floor in payment tokens
    /// * `duration_seconds` — duration over which price decays linearly from `start_price` to `floor_price`
    pub fn initialize(
        env: Env,
        seller: Address,
        asset_token: Address,
        payment_token: Address,
        asset_amount: i128,
        start_price: i128,
        floor_price: i128,
        duration_seconds: u64,
    ) {
        seller.require_auth();

        if env.storage().instance().has(&DataKey::Seller) {
            panic!("already initialized");
        }
        if asset_amount <= 0 {
            panic!("asset amount must be positive");
        }
        if start_price <= 0 || floor_price <= 0 {
            panic!("prices must be positive");
        }
        if start_price < floor_price {
            panic!("start price must be greater than or equal to floor price");
        }
        if duration_seconds == 0 {
            panic!("duration must be positive");
        }

        let now = env.ledger().timestamp();

        env.storage().instance().set(&DataKey::Seller, &seller);
        env.storage().instance().set(&DataKey::AssetToken, &asset_token);
        env.storage().instance().set(&DataKey::PaymentToken, &payment_token);
        env.storage().instance().set(&DataKey::AssetAmount, &asset_amount);
        env.storage().instance().set(&DataKey::StartPrice, &start_price);
        env.storage().instance().set(&DataKey::FloorPrice, &floor_price);
        env.storage().instance().set(&DataKey::StartTime, &now);
        env.storage().instance().set(&DataKey::Duration, &duration_seconds);
        env.storage().instance().set(&DataKey::State, &AuctionState::Pending);
    }

    /// Deposit the asset tokens into the auction contract to open the auction.
    ///
    /// Must be called by the `seller` after `initialize`.
    pub fn fund(env: Env) {
        let state: AuctionState = env
            .storage()
            .instance()
            .get(&DataKey::State)
            .expect("auction not initialized");
        if state != AuctionState::Pending {
            panic!("auction can only be funded when pending");
        }

        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        seller.require_auth();

        let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();

        let client = token::Client::new(&env, &asset_token);
        client.transfer(&seller, &env.current_contract_address(), &asset_amount);

        env.storage().instance().set(&DataKey::State, &AuctionState::Open);
    }

    /// Calculate and return the current price based on elapsed time.
    ///
    /// Linear decay: price = start_price - ((start_price - floor_price) * elapsed / duration)
    /// If timestamp <= start_time, returns start_price.
    /// If timestamp >= start_time + duration, returns floor_price.
    pub fn get_current_price(env: Env) -> i128 {
        let start_price: i128 = env.storage().instance().get(&DataKey::StartPrice).unwrap();
        let floor_price: i128 = env.storage().instance().get(&DataKey::FloorPrice).unwrap();
        let start_time: u64 = env.storage().instance().get(&DataKey::StartTime).unwrap();
        let duration: u64 = env.storage().instance().get(&DataKey::Duration).unwrap();

        let now = env.ledger().timestamp();
        if now <= start_time {
            return start_price;
        }
        let elapsed = now - start_time;
        if elapsed >= duration {
            return floor_price;
        }

        let price_delta = (start_price - floor_price) as u128;
        let decay = (price_delta * elapsed as u128) / (duration as u128);
        start_price - (decay as i128)
    }

    /// Buy the asset at the current linearly-decayed price.
    ///
    /// The first buyer settles the auction immediately:
    /// - Transfers current price of payment tokens from buyer to seller.
    /// - Transfers asset tokens from contract to buyer.
    /// - Sets auction state to `Settled`.
    pub fn buy(env: Env, buyer: Address) -> i128 {
        buyer.require_auth();

        let state: AuctionState = env
            .storage()
            .instance()
            .get(&DataKey::State)
            .expect("auction not initialized");
        if state != AuctionState::Open {
            panic!("auction is not open for purchase");
        }

        let current_price = Self::get_current_price(env.clone());

        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        let payment_token: Address = env.storage().instance().get(&DataKey::PaymentToken).unwrap();
        let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();

        // Transfer payment from buyer to seller
        let payment_client = token::Client::new(&env, &payment_token);
        payment_client.transfer(&buyer, &seller, &current_price);

        // Transfer asset from contract to buyer
        let asset_client = token::Client::new(&env, &asset_token);
        asset_client.transfer(&env.current_contract_address(), &buyer, &asset_amount);

        env.storage().instance().set(&DataKey::State, &AuctionState::Settled);
        env.storage().instance().set(&DataKey::Buyer, &buyer);
        env.storage().instance().set(&DataKey::SettledPrice, &current_price);

        current_price
    }

    /// Cancel the auction before purchase and reclaim asset tokens.
    ///
    /// Must be called by `seller`.
    pub fn cancel(env: Env) {
        let seller: Address = env.storage().instance().get(&DataKey::Seller).unwrap();
        seller.require_auth();

        let state: AuctionState = env
            .storage()
            .instance()
            .get(&DataKey::State)
            .expect("auction not initialized");
        if state != AuctionState::Open {
            panic!("can only cancel an open auction");
        }

        let asset_token: Address = env.storage().instance().get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = env.storage().instance().get(&DataKey::AssetAmount).unwrap();

        let asset_client = token::Client::new(&env, &asset_token);
        asset_client.transfer(&env.current_contract_address(), &seller, &asset_amount);

        env.storage().instance().set(&DataKey::State, &AuctionState::Canceled);
    }

    /// Return current state of the auction.
    pub fn get_state(env: Env) -> AuctionState {
        env.storage()
            .instance()
            .get(&DataKey::State)
            .expect("auction not initialized")
    }
}

#[cfg(test)]
mod test;
