//! A caller contract that invokes another contract across the boundary.
//!
//! This contract demonstrates:
//! 1. How to generate a client for the called contract
//! 2. How to invoke the contract via that client
//! 3. How authorization requirements propagate from the called contract back
//!    to the original transaction's authorization entries
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use receiver::ReceiverClient;
use soroban_sdk::{contract, contractimpl, Address, Env, Symbol};

#[contract]
pub struct Caller;

#[contractimpl]
impl Caller {
    /// Invoke the receiver contract's authorized_action function.
    ///
    /// This demonstrates a cross-contract call. The `target_user` parameter
    /// is passed to the receiver contract, which will call `require_auth()` on it.
    /// The authorization from the original transaction automatically propagates
    /// through this call.
    ///
    /// # Arguments
    /// * `receiver_address` - The address of the deployed receiver contract
    /// * `target_user` - The user who authorizes the action (passed to receiver)
    /// * `message` - The message to pass through to the receiver
    ///
    /// Returns the message confirming the call succeeded.
    pub fn invoke_receiver(
        env: Env,
        receiver_address: Address,
        target_user: Address,
        message: Symbol,
    ) -> Symbol {
        // Create a client for the receiver contract
        let receiver = ReceiverClient::new(&env, &receiver_address);

        // Call the receiver's authorized_action method
        // The target_user's authorization requirement propagates to this transaction
        let result = receiver.authorized_action(&target_user, &message);

        // Emit an event to log the cross-contract call
        env.events()
            .publish(("caller", "invoked_receiver"), (&target_user, &message));

        result
    }
}

#[cfg(test)]
mod test;
