//! NFT Marketplace contract.
//!
//! Allows listing, buying, and cancelling NFT sales with a configurable
//! protocol fee sent to a treasury address. Built to interact with NFTs
//! conforming to the `nft` template's interface.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{
    contract, contractclient, contracterror, contractimpl, contracttype, panic_with_error,
    symbol_short, token, Address, Env,
};

/// Maximum fee in basis points (10000 = 100%).
pub const MAX_FEE_BPS: u32 = 10_000;

/// Ledgers per day, assuming ~5s per ledger.
pub const DAY_IN_LEDGERS: u32 = 17280;
/// Persistent data TTL (30 days).
pub const PERSISTENT_TTL: u32 = 30 * DAY_IN_LEDGERS;
/// Threshold to trigger TTL extension.
pub const PERSISTENT_TTL_THRESHOLD: u32 = PERSISTENT_TTL - DAY_IN_LEDGERS;

/// External NFT interface matching the `nft` template.
#[contractclient(name = "NftClient")]
pub trait NftInterface {
    fn transfer(env: Env, from: Address, to: Address, token_id: u32);
    fn owner_of(env: Env, token_id: u32) -> Address;
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    NotAuthorized = 1,
    AlreadyListed = 2,
    ListingNotFound = 3,
    InvalidPrice = 4,
    InvalidFee = 5,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Listing {
    pub seller: Address,
    pub nft_contract: Address,
    pub token_id: u32,
    pub payment_token: Address,
    pub price: i128,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Admin,
    Treasury,
    FeeBps,
    Listing(Address, u32),
}

fn extend_persistent_ttl(env: &Env, key: &DataKey) {
    env.storage()
        .persistent()
        .extend_ttl(key, PERSISTENT_TTL_THRESHOLD, PERSISTENT_TTL);
}

#[contract]
pub struct NftMarketplaceContract;

#[contractimpl]
impl NftMarketplaceContract {
    /// Deploy-time setup for the marketplace.
    ///
    /// * `admin` — authorized account allowed to update fee/treasury settings
    /// * `treasury` — address receiving protocol fees
    /// * `fee_bps` — protocol fee in basis points (e.g. 250 = 2.5%, max 10000)
    pub fn __constructor(env: Env, admin: Address, treasury: Address, fee_bps: u32) {
        if fee_bps > MAX_FEE_BPS {
            panic_with_error!(&env, Error::InvalidFee);
        }
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::Treasury, &treasury);
        env.storage().instance().set(&DataKey::FeeBps, &fee_bps);
    }

    /// Return the marketplace admin address.
    pub fn admin(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Admin).unwrap()
    }

    /// Return the treasury address.
    pub fn treasury(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Treasury).unwrap()
    }

    /// Return the protocol fee in basis points.
    pub fn fee_bps(env: Env) -> u32 {
        env.storage().instance().get(&DataKey::FeeBps).unwrap()
    }

    /// Update the marketplace admin address.
    /// Requires current admin authorization.
    pub fn set_admin(env: Env, new_admin: Address) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
        env.storage().instance().set(&DataKey::Admin, &new_admin);
    }

    /// Update the treasury address.
    /// Requires admin authorization.
    pub fn set_treasury(env: Env, new_treasury: Address) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
        env.storage().instance().set(&DataKey::Treasury, &new_treasury);
    }

    /// Update the protocol fee basis points.
    /// Requires admin authorization.
    pub fn set_fee_bps(env: Env, new_fee_bps: u32) {
        let admin: Address = env.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
        if new_fee_bps > MAX_FEE_BPS {
            panic_with_error!(&env, Error::InvalidFee);
        }
        env.storage().instance().set(&DataKey::FeeBps, &new_fee_bps);
    }

    /// List an NFT for sale.
    ///
    /// Escrows the NFT from `seller` to the marketplace contract.
    /// Requires `seller` authorization.
    pub fn list(
        env: Env,
        seller: Address,
        nft_contract: Address,
        token_id: u32,
        payment_token: Address,
        price: i128,
    ) {
        seller.require_auth();

        if price <= 0 {
            panic_with_error!(&env, Error::InvalidPrice);
        }

        let key = DataKey::Listing(nft_contract.clone(), token_id);
        if env.storage().persistent().has(&key) {
            panic_with_error!(&env, Error::AlreadyListed);
        }

        // Transfer NFT to marketplace for escrow
        let nft_client = NftClient::new(&env, &nft_contract);
        nft_client.transfer(&seller, &env.current_contract_address(), &token_id);

        let listing = Listing {
            seller: seller.clone(),
            nft_contract: nft_contract.clone(),
            token_id,
            payment_token,
            price,
        };

        env.storage().persistent().set(&key, &listing);
        extend_persistent_ttl(&env, &key);

        env.events()
            .publish((symbol_short!("list"), seller), (nft_contract, token_id, price));
    }

    /// Buy a listed NFT.
    ///
    /// Transfers protocol fee to treasury, net payment to seller,
    /// and the escrowed NFT to `buyer`.
    /// Requires `buyer` authorization.
    pub fn buy(env: Env, buyer: Address, nft_contract: Address, token_id: u32) {
        buyer.require_auth();

        let key = DataKey::Listing(nft_contract.clone(), token_id);
        let listing: Listing = env
            .storage()
            .persistent()
            .get(&key)
            .unwrap_or_else(|| panic_with_error!(&env, Error::ListingNotFound));

        let fee_bps: u32 = env.storage().instance().get(&DataKey::FeeBps).unwrap();
        let treasury: Address = env.storage().instance().get(&DataKey::Treasury).unwrap();

        let fee = (listing.price * fee_bps as i128) / (MAX_FEE_BPS as i128);
        let seller_amount = listing.price - fee;

        let payment_client = token::Client::new(&env, &listing.payment_token);

        if fee > 0 {
            payment_client.transfer(&buyer, &treasury, &fee);
        }
        if seller_amount > 0 {
            payment_client.transfer(&buyer, &listing.seller, &seller_amount);
        }

        // Transfer NFT from marketplace escrow to buyer
        let nft_client = NftClient::new(&env, &nft_contract);
        nft_client.transfer(&env.current_contract_address(), &buyer, &token_id);

        env.storage().persistent().remove(&key);

        env.events()
            .publish((symbol_short!("buy"), buyer), (nft_contract, token_id, listing.price));
    }

    /// Cancel an active listing and return the escrowed NFT to `seller`.
    /// Requires `seller` authorization.
    pub fn cancel(env: Env, seller: Address, nft_contract: Address, token_id: u32) {
        seller.require_auth();

        let key = DataKey::Listing(nft_contract.clone(), token_id);
        let listing: Listing = env
            .storage()
            .persistent()
            .get(&key)
            .unwrap_or_else(|| panic_with_error!(&env, Error::ListingNotFound));

        if listing.seller != seller {
            panic_with_error!(&env, Error::NotAuthorized);
        }

        // Return NFT from escrow back to seller
        let nft_client = NftClient::new(&env, &nft_contract);
        nft_client.transfer(&env.current_contract_address(), &seller, &token_id);

        env.storage().persistent().remove(&key);

        env.events()
            .publish((symbol_short!("cancel"), seller), (nft_contract, token_id));
    }

    /// Get details of an active listing, or `None` if not listed.
    pub fn get_listing(env: Env, nft_contract: Address, token_id: u32) -> Option<Listing> {
        let key = DataKey::Listing(nft_contract, token_id);
        if let Some(listing) = env.storage().persistent().get::<_, Listing>(&key) {
            extend_persistent_ttl(&env, &key);
            Some(listing)
        } else {
            None
        }
    }
}

#[cfg(test)]
mod test;
