//! A simple receiver contract that enforces authorization.
//!
//! This contract has a single entry point that requires the caller to be authorized.
//! When another contract calls this with authorization, the caller's address is
//! validated through `require_auth()`.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, Address, Env, Symbol};

#[contract]
pub struct Receiver;

#[contractimpl]
impl Receiver {
    /// Perform an authorized action with a message.
    ///
    /// Requires that `caller` authorizes this call. This is typically invoked
    /// by another contract that passes through the authorization.
    ///
    /// Returns the message to confirm the call was successful.
    pub fn authorized_action(env: Env, caller: Address, message: Symbol) -> Symbol {
        // This is the key pattern: require_auth ensures the caller is authorized.
        // When invoked via a cross-contract call, this requirement propagates
        // to the original transaction's auth_entries.
        caller.require_auth();

        // Log the event (can be viewed in transaction details)
        env.events().publish(("receiver", "action"), (&caller, &message));

        message
    }
}

#[cfg(test)]
mod test;
