//! A contract demonstrating storage migration from v1 to v2.
//!
//! This contract uses a version-marker pattern to safely migrate persistent
//! storage layouts across contract upgrades. The migration runs exactly once
//! and is idempotent.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, Env, String};

// Storage version marker key
#[contracttype]
pub enum DataKey {
    /// The current storage version (tracks migrations)
    Version,
    /// V1 storage: a simple counter
    CounterV1,
    /// V2 storage: counter + name
    CounterV2,
    NameV2,
}

// Contract version constants
const VERSION_1: u32 = 1;
const VERSION_2: u32 = 2;
const CURRENT_VERSION: u32 = VERSION_2;

fn get_version(env: &Env) -> u32 {
    env.storage()
        .instance()
        .get(&DataKey::Version)
        .unwrap_or(VERSION_1)
}

fn set_version(env: &Env, version: u32) {
    env.storage().instance().set(&DataKey::Version, &version);
}

#[contract]
pub struct StorageMigration;

#[contractimpl]
impl StorageMigration {
    /// Initialize the contract with a counter and name (v2 layout).
    ///
    /// This also ensures that any v1 state is migrated to v2.
    pub fn init(env: Env, initial_counter: u32, name: String) {
        // Run migration if needed
        Self::migrate_if_needed(&env);

        // Set the v2 state
        env.storage().instance().set(&DataKey::CounterV2, &initial_counter);
        env.storage().instance().set(&DataKey::NameV2, &name);
        set_version(&env, CURRENT_VERSION);
    }

    /// Run the storage migration from v1 to v2.
    ///
    /// This function is idempotent and safe to call multiple times.
    /// It only performs the migration once (checked via version marker).
    fn migrate_if_needed(env: &Env) {
        let current_version = get_version(env);

        if current_version >= CURRENT_VERSION {
            return; // Already migrated
        }

        if current_version == VERSION_1 {
            Self::migrate_v1_to_v2(env);
        }

        set_version(env, CURRENT_VERSION);
    }

    /// Migrate from v1 to v2 storage layout.
    ///
    /// v1 layout: { counter: u32 }
    /// v2 layout: { counter: u32, name: String }
    ///
    /// This reads the v1 counter and preserves it in v2, while adding
    /// a default name field.
    fn migrate_v1_to_v2(env: &Env) {
        // Read v1 counter
        let v1_counter: u32 = env
            .storage()
            .instance()
            .get(&DataKey::CounterV1)
            .unwrap_or(0);

        // Write to v2 storage
        env.storage()
            .instance()
            .set(&DataKey::CounterV2, &v1_counter);
        env.storage()
            .instance()
            .set(&DataKey::NameV2, &String::from_slice(env, "migrated"));

        // Optionally: remove v1 keys to clean up
        // env.storage().instance().remove(&DataKey::CounterV1);
    }

    /// Get the current counter value (v2 layout).
    pub fn get_counter(env: Env) -> u32 {
        Self::migrate_if_needed(&env);
        env.storage()
            .instance()
            .get(&DataKey::CounterV2)
            .unwrap_or(0)
    }

    /// Get the current name (v2 layout).
    pub fn get_name(env: Env) -> String {
        Self::migrate_if_needed(&env);
        env.storage()
            .instance()
            .get(&DataKey::NameV2)
            .unwrap_or_else(|| String::from_slice(&env, "unknown"))
    }

    /// Increment the counter (v2 layout).
    pub fn increment(env: Env) {
        Self::migrate_if_needed(&env);
        let current: u32 = env
            .storage()
            .instance()
            .get(&DataKey::CounterV2)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&DataKey::CounterV2, &(current + 1));
    }

    /// Update the name (v2 layout).
    pub fn set_name(env: Env, new_name: String) {
        Self::migrate_if_needed(&env);
        env.storage()
            .instance()
            .set(&DataKey::NameV2, &new_name);
    }

    /// Get the current storage version.
    ///
    /// Useful for testing and debugging migrations.
    pub fn version(env: Env) -> u32 {
        get_version(&env)
    }
}

#[cfg(test)]
mod test;
